### PR TITLE
Fix HDR temporarily

### PR DESCRIPTION
**Pull request by Nonta72**
Taken from https://github.com/aquaris-dev/proprietary_vendor_bq/tree/cm-14.1/vegetalte

**Fixes HDR in some camera apps:**
- BQ Camera 4.5.2 signed = **OK**
- Google Camera 2.7 = **OK**
- Lenovo SnapIt 5.8 = **OK**
- Snap Camera = **NOT WORKING** (takes double pictures).

### CODE REVIEW

**Comment by Nonta72** [comment]
Slowmotion is still broken in BQ Camera

**Comment by stucki** [comment]
Using the blobs from a different device will probably have new implications. I prefer to fix the root of the problem. See https://github.com/aquaris-dev/android_device_bq_gohan/issues/9

**Comment by Nonta72** [comment]
Yeah, it's never a good idea.
But HDR was fixed at some point in CM/LOS13 using blobs from kipper.
So, I'd say this fix is better than nothing. It's not final of course, that's why I used "Temporary".
We will try when BQ releases OFFICIAL Nougat for this device.

**Comment by eloimuns** [comment]
I do not agree this changes. 

We will upgrade  tree/blobs/kernel to 5.0.0 so "it should be fixed" at this point.

**Comment by Nonta72** [comment]
As you wish.

**Pull request closed without merging**
